# Generated by Django 4.1.5 on 2023-01-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gruop',
        ),
        migrations.AddField(
            model_name='profile',
            name='gruop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
           
        ),
    ]
